#
# Copyright (c) 2018 SUSE
#
# SPDX-License-Identifier: Apache-2.0

ARG IMAGE_REGISTRY=docker.io
# NOTE: OS_VERSION is set according to config.sh
FROM ${IMAGE_REGISTRY}/debian:trixie

ENV GO_HOME="/opt"
ENV GOCACHE="${GO_HOME}/.cache"
ENV RUSTUP_HOME="/opt/rustup"
ENV CARGO_HOME="/opt/cargo"
ENV PATH="/opt/cargo/bin/:/opt/go/bin:${PATH}"

ARG GO_VERSION
ARG RUST_TOOLCHAIN=1.85.1
ENV PATH="/opt/go/bin:${PATH}"

RUN echo "${RUST_TOOLCHAIN}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN mkdir ${RUSTUP_HOME} ${CARGO_HOME} ${GOCACHE} && \
    chmod -R a+rwX ${RUSTUP_HOME} ${CARGO_HOME} ${GO_HOME}

RUN [ -x /usr/bin/systemd-detect-virt ] || ( echo "echo docker" >/usr/bin/systemd-detect-virt && chmod +x /usr/bin/systemd-detect-virt )


# RUN commands
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive\
    apt-get --no-install-recommends install -y \
    apt-utils \
    autoconf \
    automake \
    binutils \
    mmdebstrap \
    build-essential \
    ca-certificates \
    chrony \
    coreutils \
    curl \
    debianutils \
    debootstrap \
    g++ \
    gcc \
    git \
    libc-dev \
    libstdc++-12-dev \
    m4 \
    make \
    musl-tools \
    sed \
    jq \
    systemd \
    tar \
    vim \
    wget \
    xz-utils \
    pip \
    python3-dev \
    libclang-dev \
    file \
    zstd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

#Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --no-modify-path --default-toolchain 1.85.1
# Link MUSL
RUN if [ ! -f "/usr/bin/$(uname -m)-linux-musl-gcc" ]; then ln -s /usr/bin/musl-gcc "/usr/bin/$(uname -m)-linux-musl-gcc"; fi

# MUSL Config
RUN ARCH=$(uname -m); \
    rust_arch=""; \
    libc=""; \
    case "${ARCH}" in \
    ("aarch64") rust_arch="${ARCH}"; libc="musl"; ;; \
    ("ppc64le") rust_arch="powerpc64le"; libc="gnu"; ;; \
    ("x86_64") rust_arch="${ARCH}"; libc="musl"; ;; \
    ("s390x") rust_arch="${ARCH}"; libc="gnu"; ;; \
    (*) echo "Unsupported architecture: ${ARCH}" && exit 1 ;; \
    esac; \
    rustup target add "${rust_arch}-unknown-linux-${libc}"


